services:
  backend:
    build: Back-End/
    container_name: arcaptcha_backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./Back-End/db/:/app/db
  
  frontend:
    build: Front-End/
    container_name: arcaptcha_frontend
    ports:
      - 8080:80
    depends_on:
      - backend