services:
  backend:
    build: Back-End/
    container_name: arcaptcha_backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./Back-End/db/:/app/db
      - ./Back-End/logs/:/app/logs

    depends_on:
      - postgres

  frontend:
    build: Front-End/
    container_name: arcaptcha_frontend
    ports:
      - 8080:80
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: arcaptcha_rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    build: postgres/
    container_name: arcaptcha_postgres
    env_file:
      - ./postgres/.env.postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
