services:
  backend:
    build: Back-End/
    container_name: arcaptcha_backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_TYPE=file
      - JWT_SECRET=testsecret
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - ARCAPTCHA_SITEKEY=rvr5q8ovqn
      - ARCAPTCHA_SECRETKEY=ok1kmzuwxjtiak4rd2wl
    volumes:
      - ./Back-End/db/:/app/db
  
  frontend:
    build: Front-End/
    container_name: arcaptcha_frontend
    ports:
      - 8080:80
    depends_on:
      - backend